name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "JDK ${{ matrix.java }}"
    strategy:
      matrix:
        java: [ 8, 11, 15 ]
    runs-on: ubuntu-latest
    steps:
      # Cancel any previous runs for the same branch that are still running.
      - name: 'Cancel previous runs'
        uses: styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5
        with:
          access_token: ${{ github.token }}
      - name: 'Check out repository'
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: 'Cache local Maven repository'
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: 'Install'
        shell: bash
        run: mvn -B install -U -DskipTests=true
      - name: 'Test'
        shell: bash
        run: mvn -B verify -U -Dmaven.javadoc.skip=true
